# Generated by Django 5.1.5 on 2025-02-10 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="favorited_by",
        ),
        migrations.AddField(
            model_name="event",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="saved_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
