# Generated by Django 5.1.5 on 2025-02-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_favorited_by_attendance_event_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
