# Generated by Django 5.1.5 on 2025-02-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="security_answer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="security_question",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
